#!/bin/bash

if [ -z "$1" ]; then
  echo "No text specified, usage: ftext text_to_find"
else
  # exec find . -type f -exec grep --color=always $1 '{}' \; -print
  exec grep --color=always -rnw '.' -e $1
fi
